### ISSUE TITLE
Payment Breakdown

### ISSUE THREAD

**Issue by AndyGabler** [frap129/cs471-project#14] opened 2021-04-21 00:02 UTC
As a member of the registrar, I would like a screen to see the amount of payment I can expect from a student after loans have been applied.

**Acceptance Criteria**
| User Action | System Response |
|---|---|
| Registrar accesses loan web page | Web page prompts login |
| Registrar logs in | Web page responds with either success or failure |
| Registrar navigates to user list | Web page responds with list of students available to registrar |
| Registrar selects student and navigates to payment details | Web page provides details of student payment, including how much the student will have to pay after their loans |

**Comment by TytanRock** [comment] 2021-05-30 15:22
Duplicate of reworked #13

**Closed by TytanRock** 2021-05-30 15:22 UTC
Labels: registrar, story
